var settings = {
  "service": "Twitch",
  "deepbot": false,
  "nightbot": true,
  "phantombot": false,
  "streamelements": true,
  "wizebot": false,
  "imperial": true,
  "srenabled": true,
  "srmessage": "{0} in order to request a song you need to add a song/video ID, url or a search term",
  "excluded": "",
  "ytuser": "UJs2dkKKK92Gmki01IiE2w",
  "giphyapikey": "KBU47FtdqBMZc7yHAcLuyUFyhWwwKqvi",
  "giphyimageurl": "https://i.giphy.com/media/{0}/200w_d.gif",
  "giphyfailid": "u2TrRPK8J6Bwc",
  "giphytype": "gifs",
  "giphyrating": "R",
  "language": "en",
  "time": "%H:%M:%S",
  "date": "%d/%m-%Y",
  "twitteruser": "",
  "norts": true,
  "tweeturl": true,
  "tweetshort": true,
  "tweethowlong": true,
  "ctt": "Come join me over at twitch.tv/$mychannel",
  "cttfailed": "Failed to update click to tweet link!",
  "volume": 50.0
};